URL: https://cloud.idste.org/
log:
    file_name : test.log
    backup : 5
    console_level: WARNING
    file_level: DEBUG
    pattern : '%(asctime)s - %(filename)s -%(name)s - %(levelname)s - %(message)s'

TEST1 : 1

